version: '3.8'

services:
  web:
    build: .
    image: project-lab-app-web
    depends_on:
      db:
        condition: service_healthy
        restart: true
    env_file:
      - .env
    ports:
      - 3000:3000
    # volumes:
    #   - .:/usr/src/app
    command: /bin/main
    # command: air cmd/main.go -b 0.0.0.0
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h db -U juan1234 || exit 1"]
      interval: 5s
      timeout: 10s
      retries: 3
    volumes:
     - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db: